.

diff --git a/systems/generic b/systems/generic
--- a/systems/generic
+++ b/systems/generic
@@ -1,7 +1,4 @@
 #!/bin/bash 
-#system_cores_per_node="$(getconf _NPROCESSORS_ONLN 2>/dev/null)"
-#system_max_cores_per_node="$system_cores_per_node"
-
 GenerateJobfileHeader() {
     return 0
 }
@@ -9,15 +6,21 @@ GenerateJobfileHeader() {
 GenerateJobfileEntry() {
     mpi="$1"
     nodes="$2"
-    threads="$3"
-    exe="$4"
+    mpis="$3"
+    threads="$4"
+    exe="$5"
+
+    if (( $nodes > 1 )); then
+        >&2 echo "Error: generic systems do not support multi-node execution"
+        exit 1
+    fi
 
     case "$mpi" in 
         none)
             echo "$exe"
             ;;
         OpenMPI)
-            echo "mpirun -n $nodes --bind-to core --map-by socket:PE=${threads} $exe"
+            echo "mpirun -n $mpis --bind-to core --map-by socket:PE=${threads} $exe"
             ;;
         *)
             >&2 echo "Error: unsupported MPI $mpi"
