feat: add OpenMPI support for SuperMUC

diff --git a/systems/SuperMUC b/systems/SuperMUC
--- a/systems/SuperMUC
+++ b/systems/SuperMUC
@@ -74,22 +74,27 @@ GenerateJobfileHeader() {
     fi
     echo "#SBATCH --partition=$partition"
 
-    echo "module restore $ROOT/data/SuperMUC/modules-impi"
-
-    if [[ "${args[mpi]}" != "IMPI" ]]; then
-        >&2 echo "Error: application must be run with IMPI"
-        exit 1
-    fi
+    case "${args[mpi]}" in
+        IMPI)
+            echo "module restore $ROOT/data/SuperMUC/modules-impi"
+            echo "export I_MPI_PIN_CELL=core"
+            echo "export I_MPI_PIN_DOMAIN=${args[num_threads]}:compact"
+    
+            #if [[ "${args[timelimit]}" != "0" ]]; then 
+                #echo "export I_MPI_JOB_TIMEOUT=${args[timelimit]}"
+            #fi
+            ;;
+        OpenMPI)
+            echo "module restore $ROOT/data/SuperMUC/modules-openmpi"
+            ;;
+        *)
+            >&2 echo "Error: unsupported MPI ${args[mpi]}"
+            exit 1
+    esac
 
     echo "unset OMP_NUM_THREADS"
     echo "unset OMP_PROC_BIND"
     echo "unset OMP_PLACES"
-    
-    echo "export I_MPI_PIN_CELL=core"
-    echo "export I_MPI_PIN_DOMAIN=${args[num_threads]}:compact"
-    #if [[ "${args[timelimit]}" != "0" ]]; then 
-        #echo "export I_MPI_JOB_TIMEOUT=${args[timelimit]}"
-    #fi
 }
 
 GenerateJobfileEntry() {
@@ -100,17 +105,26 @@ GenerateJobfileEntry() {
     fi
 
     case "${args[mpi]}" in
-        none)
-            >&2 echo "Error: application must be run with MPI"
-            exit 1
-            ;;
         IMPI)
+            if [[ "${args[print_wrapper]}" == "1" ]]; then
+                >&2 echo -e "mpiexec -n $ARGS_COLOR$((args[num_nodes]*args[num_mpis]))$NO_COLOR --perhost $ARGS_COLOR${args[num_mpis]}$NO_COLOR <call>"
+            fi
             echo "mpiexec -n $((args[num_nodes]*args[num_mpis])) --perhost ${args[num_mpis]} ${args[exe]}"
+            ;;
+        OpenMPI)
+            if [[ "${args[print_wrapper]}" == "1" ]]; then
+                >&2 echo -e "  - mpirun -n $ARGS_COLOR$((args[num_nodes]*args[num_mpis]))$NO_COLOR --bind-to core --map-by socket:PE=$ARGS_COLOR${args[num_threads]}$NO_COLOR <call>"
+            fi
+            echo "mpirun -n $((args[num_nodes]*args[num_mpis])) --bind-to core --map-by socket:PE=${args[num_threads]} ${args[exe]}"
             ;;
         *)
             >&2 echo "Error: unsupported MPI ${args[mpi]}"
             exit 1
     esac
+
+    if [[ "${args[print_wrapper]}" == "1" ]]; then
+        >&2 echo ""
+    fi
 }
 
 GenerateJobfileSubmission() {
